name: "pre-merge"
run-name: ${{ github.actor }} is running pre-merge checks
on: pull_request
jobs:
  pre-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run type checks
        run: pnpm check-types
      - name: Run linting
        run: pnpm lint
      - name: Run linting
        run: pnpm lint
      - name: Build
        run: pnpm build
